services:
  api:
    image: ghcr.io/mahir41204/cliniqflow-api:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://clinic:clinic123@postgres:5432/clinic_db
      - FRONTEND_URL=https://cliniqflow.pages.dev

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=clinic
      - POSTGRES_PASSWORD=clinic123
      - POSTGRES_DB=clinic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
volumes:
  postgres_data:
  